### PR TITLE
IN-1243

### PR DESCRIPTION
**Pull request by lmesz-bitrise**
Update our fork to be align to homebrew/homebrew-core

### CODE REVIEW

**Comment by Szabadember** [comment]
master should be updated by pulling the original master into the fork's master

**Comment by leohidalgo** [comment]
This fork is quite out of date, was there a problem?

**Comment by lmesz-bitrise** [comment]
No there wasn't any problem. We will update it and create a regular update.

**Comment by leohidalgo** [comment]
You currently have a may 28 version 🙁. Do you know when it will be updated?

**Pull request closed without merging**
